<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Radcheck extends Model
{
    protected $fillable = [
        'username',
        'attribute',
        'op',
        'value',
        'enablemac',
        'macaddress',
        'ipaddress',
        'enableuser',
        'expiredate',
        'expiryextension',
        'allow_exp_connect',
        'expiredchk',
        'billcycle_id',
        'packageid',
        'sub_package_id',
        'resellerid',
        'allowpopid',
        'clientname',
        'dob',
        'clientaddress',
        'clintcontactno',
        'email',
        'clintcreatedate',
        'clientremarks',
        'tmpdel',
        'billable',
        'discount',
        'flat_level',
        'building_num',
        'building_name',
        'road_num',
        'road_name',
        'block_sector',
        'area',
        'ip_bill',
        'extra_bill',
        'rating',
        'port_id',
        'investment',
        'nid',
        'passport',
        'created_by',
        'father',
        'mother',
        'cable_meter',
        'marketed_by',
        'marketed_by_emp_id',
        'pop_disable',
        'investment_details',
        'thana',
        'district',
        'client_type',
        'vat_applicable',
        'from_tg_no',
        'from_cable_id',
        'from_cable_meter',
        'to_cable_id',
        'to_cable_meter',
        'pon_no',
        'onu_mac',
        'vlan_id',
        'from_google_gps',
        'to_google_gps',
        'bill_collect_status',
        'billing_address',
        'connected_by',
        'last_power',
        'alternative_contact',
        'approved_by',
        'approved_datetime',
        'deposit',
        'alternative_contact_2',
        'police_station',
        'connect_via',
        'olt_number',
        'olt_slot',
        'marketing_method',
        'comments',
        'cable_operator',
        'connected_to',
        'paid_via',
        'original_package_id',
        'gpon_epon',
        'deposit_remarks',
    ];

    protected function casts(): array
    {
        return [
            'enablemac' => 'integer',
            'enableuser' => 'boolean',
            'expiredate' => 'date',
            'expiryextension' => 'date',
            'allow_exp_connect' => 'integer',
            'expiredchk' => 'integer',
            'billcycle_id' => 'integer',
            'sub_package_id' => 'integer',
            'allowpopid' => 'integer',
            'dob' => 'date',
            'clintcreatedate' => 'datetime',
            'tmpdel' => 'integer',
            'billable' => 'integer',
            'discount' => 'integer',
            'ip_bill' => 'integer',
            'extra_bill' => 'integer',
            'rating' => 'decimal:1',
            'port_id' => 'integer',
            'investment' => 'integer',
            'created_by' => 'integer',
            'cable_meter' => 'integer',
            'marketed_by_emp_id' => 'integer',
            'pop_disable' => 'integer',
            'vat_applicable' => 'integer',
            'approved_by' => 'integer',
            'approved_datetime' => 'datetime',
            'deposit' => 'integer',
            'connect_via' => 'integer',
            'olt_number' => 'integer',
            'original_package_id' => 'integer',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ];
    }
}
